### ISSUE TITLE
remove initial state from helpers

### ISSUE THREAD

**Issue by Partyschaum** [Jimdo/grunt-angular-toolbox#2]
in order to require the toolbox before initial config
(see https://github.com/Jimdo/angular-awesome-background/commit/52c4e737d85ce222b6a7e3f9fd2c917cfb33a96e)

**Comment by Xiphe** [comment]
should work now with version 1.0
helper does not exists anymore, though.

settings etc. are directly in the grunt config and consumable using `grunt.config('angularToolbox.templates.banner')` or `'<%= angularToolbox.templates.banner %>'`

will test that and close if fine.

**Comment by Xiphe** [comment]
`'<%= angularToolbox.templates.banner %>'` works fine

**Comment by Xiphe** [comment]
helpers are removed, no current plans to re-add them
